universe 		= docker
docker_image 		= nik1806/mlcysec:1.0
executable              = executable_cmd.sh
output                  = exp.$(ClusterId).$(ProcId).out
error                   = exp.$(ClusterId).$(ProcId).err
log                     = exp.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = .
request_GPUs = 1
request_CPUs = 1
request_memory = 1G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1
